### ISSUE TITLE
Take Python 2.5 out of the list of supported Pythons if not being tested for it.

### ISSUE THREAD

**Issue by pydanny** [michaeljohnbarr/django-timezone-utils#1]
The Travis config file goes no further down than 2.6. 

Nice project! can't wait to try it out!

**Comment by mbarrtribridge** [comment]
Ah, thank you! I certainly do need to test for it as it is supported in Django 1.4! I will update that ASAP.

**Comment by michaeljohnbarr** [comment]
Ah, thank you! I certainly do need to test for it as it is supported in Django 1.4! I will update that ASAP.

**Comment by michaeljohnbarr** [comment]
Correction - apparently, travis-ci only supports Python 2.6+. You live, you learn. I will be removing it from the trove classifiers.

**Comment by michaeljohnbarr** [comment]
Closing. Should be fixed with the release of https://github.com/michaeljohnbarr/django-timezone-utils/tree/v0.4

**Comment by pydanny** [comment]
For a number of projects that I maintain I've stopped supporting Python 2.6. Makes a lot of things easier to implement. ;)
