### ISSUE TITLE
RemovedInDjango110Warning: SubfieldBase has been deprecated

### ISSUE THREAD

**Issue by djch** [michaeljohnbarr/django-timezone-utils#7]
Noticed a weird deprecation warning coming from Django 1.9 and tracked it down to this plug-in (which is very useful, thanks for maintaining it).

```
/venv/lib/python2.7/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
```

Refs:
- #3 
- https://github.com/michaeljohnbarr/django-timezone-utils/blob/03758d2907a026bd337f8e1f50e3cc902ada922e/timezone_utils/fields.py#L27

**Comment by djch** [comment]
Turns out I might have got your plugin confused with a similarly-titled plugin which also uses `SubfieldBase` ... sorry.

Feel free to close this, assuming it's not relevant 😅

**Comment by michaeljohnbarr** [comment]
Yes, we conditionally use `models.SubfieldBase` if it is available. I believe it is safe to completely remove this once we fully deprecate support for Django 1.7 and below. According to the [Django 1.8 Release Notes](https://docs.djangoproject.com/en/1.8/releases/1.8/#subfieldbase), this was deprecated in Django 1.8, so I don't believe that Django 1.8 would be using it anywhere. I am going to leave this ticket open until such a time that this package drops support for versions prior to Django 1.8.
